//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocLapTrinhWeb.BLL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NHATNAM\\SQLEXPRESS;Initial Catalog=MyLife;Persist Security Info=True;" +
            "User ID=vnn;Password=123456")]
        public string MyLifeConnectionString {
            get {
                return ((string)(this["MyLifeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlExpress;Initial Catalog=HocLapTrinhWeb_MyLife;User ID=vnn;Passwo" +
            "rd=123456")]
        public string HocLapTrinhWeb_MyLifeConnectionString {
            get {
                return ((string)(this["HocLapTrinhWeb_MyLifeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.90\\SQLExpress;Initial Catalog=HocLapTrinhWeb_MyLife;Persis" +
            "t Security Info=True;User ID=vnn;Password=123456")]
        public string HocLapTrinhWeb_MyLifeConnectionString1 {
            get {
                return ((string)(this["HocLapTrinhWeb_MyLifeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VONHATNAM-PC;Initial Catalog=HLTW;Persist Security Info=True;User ID=" +
            "vnn;Password=123456")]
        public string HLTWConnectionString {
            get {
                return ((string)(this["HLTWConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VONHATNAM-PC;Initial Catalog=HocLapTrinhWeb_MyLife;User ID=vnn;Passwo" +
            "rd=123456")]
        public string HocLapTrinhWeb_MyLifeConnectionString2 {
            get {
                return ((string)(this["HocLapTrinhWeb_MyLifeConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.213.89.57;Initial Catalog=HocLapTrinhWeb_MyLife;Persist Security " +
            "Info=True;User ID=vnn;Password=123456")]
        public string HocLapTrinhWeb_MyLifeConnectionString3 {
            get {
                return ((string)(this["HocLapTrinhWeb_MyLifeConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Nhatnam;Initial Catalog=HocLapTrinhWeb_MyLife;Persist Security Info=T" +
            "rue;User ID=sa;Password=vnn123456")]
        public string HocLapTrinhWeb_MyLifeConnectionString4 {
            get {
                return ((string)(this["HocLapTrinhWeb_MyLifeConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VONHATNAM-PC\\SQLServerR2;Initial Catalog=HLTW_MyLife;User ID=sa;Passw" +
            "ord=vnn123456")]
        public string HLTW_MyLifeConnectionString {
            get {
                return ((string)(this["HLTW_MyLifeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=112.213.89.157;Initial Catalog=HocLapTrinhWeb_MyLife;Persist Security" +
            " Info=True;User ID=vnn;Password=123456")]
        public string HocLapTrinhWeb_MyLifeConnectionString5 {
            get {
                return ((string)(this["HocLapTrinhWeb_MyLifeConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NHATNAM;Initial Catalog=HLTW_MyLife;Persist Security Info=True;User I" +
            "D=sa;Password=vnn123456")]
        public string HLTW_MyLifeConnectionString1 {
            get {
                return ((string)(this["HLTW_MyLifeConnectionString1"]));
            }
        }
    }
}
